fileGroups:
  elmSources:
    - "src"
tasks:
  elm-lint:
    command: |
      elm-format @dirs(elmSources) @files(elmSources) --validate --yes
    inputs:
      - "@files(elmSources)"

  elm-format:
    command: |
      elm-format @dirs(elmSources) @files(elmSources) --yes
    inputs:
      - "@files(elmSources)"
  test:
    inputs: []
    deps:
      - target: "~:scala-jvm"
        optional: true
      - target: "~:elm-test"
        optional: true